# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1901087eebe2380db62c493560fa6052ec3d266d712f25b15c4d980bde97ba89ae76d63a5da89da25722161740a5e0cbf59659aaf4417df27da2ae6f44ec0e23

test:
  secret_key_base: ed2a9eefc5ad3389d7b47d9e26d2b84bd26cdbe08e47063cbaef575da04f4151852f37a91289ed1f84353d24c0e3ed90e52b3f5f3bfbb9850b98626fa2931fce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
